In [2]:
import numpy as np

In [10]:
arr = np.array([23,45,34,56,75.8,'sohil',23,54])
arr
# similar type store

array(['23', '45', '34', '56', '75.8', 'sohil', '23', '54'], dtype='<U32')

In [4]:
type(arr)

numpy.ndarray

In [6]:
len(arr)

7

In [11]:
arr.dtype

dtype('<U32')

In [9]:
print(np.__version__)

2.0.0


In [12]:
arr = np.array([23,45,34,56,75,23,54])
arr

array([23, 45, 34, 56, 75, 23, 54])

In [16]:
arr[1:5]

array([45, 34, 56, 75])

In [18]:
arr[-1] = 500
arr

array([ 23,  45,  34,  56,  75,  23, 500])

In [19]:
arr + 2

array([ 25,  47,  36,  58,  77,  25, 502])

In [20]:
arr * 2

array([  46,   90,   68,  112,  150,   46, 1000])

In [29]:
## 2D arrays 

In [33]:
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
type(ls)

list

In [34]:
ls[-1]

[7, 8, 9]

In [37]:
arr2 = np.array(ls)
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2[0]

array([1, 2, 3])

In [41]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2[1,1:]

array([5, 6])

In [43]:
arr2[1:,2:]

array([[6],
       [9]])

In [46]:
arr2[-2:,-2]

array([5, 8])

In [48]:
arr2[-1,-1] = 90
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [56]:
arr = np.random.randint(1,200,500)
arr

array([ 18, 132, 129,  98, 144, 184,  53, 103, 166,  56, 168, 171,  66,
        82,  65,  20, 118,  65, 146,  92,  14, 117, 188,  19, 188, 184,
       131, 137, 180,  51,   8, 172, 143,   6,  83,  85,  99,   3,  41,
         9, 190,  88,  23, 194, 179,  32, 146,  93,  42,   9,  36,  16,
       145, 155, 180, 123, 146, 195, 168,  35,  25, 195,  99, 150,  16,
        81, 129,  89, 124,  77,  65,   1,  26, 157, 118, 189, 106,  74,
       159, 143,  50, 124, 137, 107,  99, 131, 121, 181, 110, 120, 162,
        70, 119,  21, 155,  13,  67, 137, 158, 161, 193,  22,  24,  34,
       157,  36,  84, 176, 136, 189,  31,  57, 185,  96,  46,  32,  57,
        13, 164,  83,   8, 154,  42,  51, 103,  25, 119,  85,  91,  65,
       120,   9, 153, 139,  54,  46, 113, 175, 183,  19,  77, 157,  90,
        60, 103, 189,  66,  29, 132,  60,   4, 124,  91, 168, 111,  85,
        97, 145, 170, 159,  37, 119,  43,  77,  68,  59,  30,  86,  56,
        79,  83, 190,  45, 170,  85,  17,  49, 178, 110, 139,  4

In [57]:
len(arr)

500

In [63]:
arr[arr <= 100]

array([ 18,  98,  53,  56,  66,  82,  65,  20,  65,  92,  14,  19,  51,
         8,   6,  83,  85,  99,   3,  41,   9,  88,  23,  32,  93,  42,
         9,  36,  16,  35,  25,  99,  16,  81,  89,  77,  65,   1,  26,
        74,  50,  99,  70,  21,  13,  67,  22,  24,  34,  36,  84,  31,
        57,  96,  46,  32,  57,  13,  83,   8,  42,  51,  25,  85,  91,
        65,   9,  54,  46,  19,  77,  90,  60,  66,  29,  60,   4,  91,
        85,  97,  37,  43,  77,  68,  59,  30,  86,  56,  79,  83,  45,
        85,  17,  49,  48,  33,  24,  59,  27,  71,  28,  14,  66,   8,
        95,  25,  21, 100,  10,  40,  91,  36,  82,  97,  35,  74,  12,
        57,  39,  82,  14,  15,  62,   3,  44,  99,  15,  34,  36,  94,
         6,  74,  37,  55,  61,  95,  10,  28, 100,  27,  45,  72,  57,
        48,  17,  62,  56,   2,  87,  60,  44,  76,  23,  61,  63,  75,
        73,  47,  33,  31,  57,  48,  28,  10,  40,   3,  46,  44,  33,
        63,  46,  97,  36,  12,  28,   2,  46,  99,  32,  57,  4

In [64]:
arr[arr <= 100].size

251

In [65]:
len(arr[arr <= 100])

251

In [66]:
arr[arr <= 100].shape

(251,)

In [69]:
arr2 = np.random.randint(1,200,(10,6))  # row , column
arr2

array([[ 14,  95, 198,  52, 174,  99],
       [ 57, 102, 196,  81, 169, 194],
       [ 10,   7, 140,  36,  67,  83],
       [ 95, 180, 157, 109,  80,  75],
       [ 73, 131, 141, 181, 185,  54],
       [198,  66, 172,  35,  97, 101],
       [ 90, 107, 161,  64,  36, 183],
       [124,  98,  24,  23, 177,  61],
       [ 30, 192, 194, 181, 156,  63],
       [ 43,  50, 166, 109, 143,  68]], dtype=int32)

In [72]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
arr.dtype

dtype('float64')

In [75]:
arr = np.zeros((10,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
arr2 = np.ones((10,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [81]:
range(10)

range(0, 10)

In [82]:
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
np.arange(10)       # only 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr = np.arange(60)
arr # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [103]:
arr = arr.reshape(6,10)   # 10 * 6 == 60
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])